---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt

  - repo: local
    hooks:
      - id: prettier-format
        name: Formatting with Prettier
        entry: npm run format
        language: node
        pass_filenames: false
        require_serial: true
